# # 状态栏位置
# set -g status on
# set -g status-position top
# set -g status-justify centre
# set -g status-interval 1
#
# # 状态栏整体颜色
# set -g status-style 'bg=#1e1e2e,fg=#cdd6f4'
#
# # Session 信息
# set -g status-left-length 30
# set -g status-left '#[fg=#1e1e2e,bg=#a6e3a1,bold] #S #[default]'
#
# # 右侧时间
# set -g status-right-length 50
# set -g status-right '#[fg=#bac2de] %Y-%m-%d  %H:%M '
#
# # 标签之间留空
# set -g window-status-separator ' '
#
# # 普通窗口
# set -g window-status-format '#[fg=#a6adc8,bg=#313244] #I:#W '
#
# # 当前窗口：蓝色高亮
# set -g window-status-current-format '#[fg=#1e1e2e,bg=#89b4fa,bold] #I:#W '
#
# # 有活动的窗口
# setw -g window-status-activity-style 'fg=#f9e2af,bg=#313244,bold'
#
# # Pane 边框
# set -g pane-border-style 'fg=#45475a'
# set -g pane-active-border-style 'fg=#89b4fa'
#
# # 鼠标点击窗口和 Pane
# set -g mouse on
#
# # 自动整理窗口编号
# set -g renumber-windows on
# set -g base-index 1
# setw -g pane-base-index 1
#


set-option -g base-index 1
# set-option -g mouse on
set-option -g renumber-windows on
set-option -g display-panes-time 1500
set-option -g escape-time 0
# set-option -g default-terminal "screen-256color"
set-option -g history-limit 20000

set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi
set-window-option -g automatic-rename on
set-window-option -g automatic-rename-format "#{pane_current_command}"
set-window-option -g monitor-activity off
set-window-option -g monitor-bell off

# 恢复默认前缀 Ctrl-b
set -g prefix M-z
unbind C-b


# 使鼠标复制只作用于一个pane里,并且选择即复制
set -g mouse on
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"



source ~/.tmuxline.conf
